# Generated by Django 2.1.1 on 2019-07-17 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='items',
            field=models.CharField(default='', max_length=500),
        ),
    ]
