# Generated by Django 2.1.1 on 2019-07-20 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0004_room__id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='_id',
        ),
    ]
